# Generated by Django 4.2.3 on 2023-07-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('country', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('street', models.TextField(max_length=50)),
                ('number_house', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('arrears', models.FloatField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.CharField(blank=True, max_length=150, null=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.contacts')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=100)),
                ('create_up_market', models.DateField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('arrears', models.FloatField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.contacts')),
                ('products', models.ManyToManyField(to='retail.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.factory')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('arrears', models.FloatField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.contacts')),
                ('products', models.ManyToManyField(to='retail.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailnetwork')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(to='retail.products'),
        ),
    ]
